-- ModuleScript: FurnitureCatalog
-- Ubicación: ReplicatedStorage > FurnitureCatalog

local FurnitureCatalog = {
	["Alfombra"] = 13,
	["Cama"] = 30,
	["Cama para mascota"] = 18,
	["Estante"] = 60,
	["Estufa"] = 55,
	["Lavamanos"] = 20,
	["Lampara"] = 10,
	["Lampara grande"] = 20,
	["Lavadora"] = 50,
	["Maceta"] = 5,
	["Mesa"] = 30,
	["Mesa media"] = 40,
	["Mueble pequeño"] = 18,
	["Refrigerador"] = 65,
	["Refrigerador moderno"] = 75,
	["Retrete"] = 30,
	["Silla"] = 20,
	["Silla moderna"] = 20,
	["Sofa"] = 45,
	["Television pequeño"] = 20,
}

return FurnitureCatalog